[general]
APP_USER = "DRITAPIPOCA"
APP_PASS = "Itapipoca2024"

[postgres]
host = "aws-0-sa-east-1.pooler.supabase.com"
port = 6543
dbname = "postgres"
user = "postgres.zjgwlvxbhyufdsqflnic"
password = "R@bson1080#"
