[general]
APP_USER = "DRITAPIPOCA"
APP_PASS = "Itapipoca2024"

[postgres]
host = "dpg-d02rfbmuk2gs73ep5nqg-a"
port = 5432
dbname = "numerador"
user = "numerador_user"
password = "7iiAufbP5T208LF6MmnvfniEiXU8CHVO"